spring:
  cache:
    type: redis
  application:
    name: GamsIBServer
  redis:
    cluster:
      nodes: @cluster.nodes@
      max-redirects: 3
    host: @redis.host@
    port: @redis.port@
    password: @redis.password@
    timeout: @redis.timeout@
    conn-type: @redis.conntype@ # cluster/single
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 2
        # 连接池中的最大空闲连接
        max-idle: 200
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 2000
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 10000
  datasource:
    master:
      jdbc-url: @master.jdbc.url@
      pool-name: @master.jdbc.poolname@
      username: @master.jdbc.username@
      password: @master.jdbc.password@
      min-idle: 2
      idle-timeout: 600000
      max-lifetime: 1800000
      maximum-pool-size: 50
      connection-timeout: 30000
      driver-class-name: oracle.jdbc.driver.OracleDriver
      connection-test-query: SELECT 'x' from dual
    slave1:
      jdbc-url: @slave1.jdbc.url@
      pool-name: @slave1.jdbc.poolname@
      username: @slave1.jdbc.username@
      password: @slave1.jdbc.password@
      min-idle: 2
      idle-timeout: 600000
      max-lifetime: 1800000
      maximum-pool-size: 50
      connection-timeout: 30000
      driver-class-name: oracle.jdbc.driver.OracleDriver
      connection-test-query: SELECT 'x' from dual
  mail:
    host: @email.host@
    port: 465 # SSL配置
    default-encoding: UTF-8
    username: @email.username@
    password: @email.password@
    test-connection: false
    properties:
      mail:
        smtp:
          auth: true # 需要验证登录名和密码
          ssl:
            enable: true
        starttls:
          enable: true # 需要TLS认证 保证发送邮件安全验证
          required: true
mybatis:
  mapper-locations: classpath*:/mybatis/**/*.xml
  check-config-location: true
  executor-type: simple
  configuration:
    jdbc-type-for-null: 'null' #注意null必须用单引号引起来
pagehelper:
  helper-dialect: @database.sql.dialect@
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
com:
  gams:
    trade: #交易端服务地址
      front:
        url: @trade.front.url@
        findPwd: /forgetPwd/stepVerify/
    emailProvider: @email.provider@ #邮件发送方式（amazon，generic）
    sms:
      host: @sms.host@
      user: @sms.user@
      pass: @sms.pass@
      inthost: @sms.inthost@
      intuser: @sms.intuser@
      intpass: @sms.intpass@
      signature:
        en: @sms.signature@
        cn: @sms.signature@
  amazon:
    ses:
      host: @amazon.ses.host@
      port: @amazon.ses.port@
      personal: @amazon.ses.personal@
      username: @amazon.ses.username@
      password: @amazon.ses.password@
      fromuser: @amazon.ses.fromuser@
  alipay:
    sofa:
      rpc:
        registry-address: @zookeeper.address@
  ib:
    gateway: #Interactive Brokers Gateway
      host: @ib.gateway.host@
      port: @ib.gateway.port@
      clientId: @ib.gateway.clientId@
logging:
  path: logs/ib
  level:
    com.fintech: @gams.logger.level@
    org.apache: info
    org.mybatis: info
  pattern:
    console: "[%d{yyyy-MM-dd HH:mm:ss:SSS}] [%p] - %pid - %l - %m%n"