server:
  port: 9000
  http2:
    enabled: true
spring:
  application:
    name: GamsOAuthServer
  thymeleaf:
    mode: LEGACYHTML5
    cache: false
    suffix: .html
    encoding: utf-8
    prefix: classpath:/templates/
  redis:
    cluster:
      nodes: @cluster.nodes@
      max-redirects: 3
    host: @redis.host@
    port: @redis.port@
    password: @redis.password@
    timeout: @redis.timeout@
    conn-type: @redis.conntype@
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 2
        # 连接池中的最大空闲连接
        max-idle: 500
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 2000
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 10000
com:
  gams:
    open-log: true
    project-name: GamsOAuthServer
    switch-remind: true
    domain-name: @domain.name@
    cookie-path: @cookie.path@
    cookie-secure: @cookie.secure@
    tradeUrl: @trade.front.url@
  alipay:
    sofa:
      rpc:
        registry-address: @zookeeper.address@
logging:
  path: logs/oauth
  level:
    com.fintech: @gams.logger.level@
    com.alipay: error
    org.apache: error
    springfox: error
  pattern:
    console: "[%d{yyyy-MM-dd HH:mm:ss:SSS}] [%p] - %pid - %l - %m%n"
