declare
    num   number;
begin
    select count(1) into num from user_tables where table_name = upper('ORGANIZE');
    if num > 0 then
        execute immediate 'drop table ORGANIZE';
    end if;
end;
/
CREATE TABLE ORGANIZE
(  ID           NUMBER(20)      NOT NULL,
   PARENT_ID    NUMBER(20),
   PATH_INFO    VARCHAR2(4000),
   ORG_CODE     VARCHAR2(64)    NOT NULL,
   ORG_NAME     VARCHAR2(128)   NOT NULL,
   ORG_DEST     VARCHAR2(256),
   SORT_NUM     NUMBER(8),
   CREATE_BY    NUMBER(20)      NOT NULL,
   CREATE_DATE  NUMBER(13)      NOT NULL,
   UPDATE_BY    NUMBER(20),
   UPDATE_DATE  NUMBER(13),
   DEL_FLAG     NUMBER(1) DEFAULT 0 NOT NULL,
   CONSTRAINT ORGANIZE_PK PRIMARY KEY (ID)
 );
COMMENT ON COLUMN ORGANIZE.ID IS '主键';
COMMENT ON COLUMN ORGANIZE.PARENT_ID IS '上级编码';
COMMENT ON COLUMN ORGANIZE.PATH_INFO IS '层级信息';
COMMENT ON COLUMN ORGANIZE.ORG_CODE IS '机构编码';
COMMENT ON COLUMN ORGANIZE.ORG_NAME IS '机构名称';
COMMENT ON COLUMN ORGANIZE.ORG_DEST IS '机构描述';
COMMENT ON COLUMN ORGANIZE.SORT_NUM IS '排序号';
COMMENT ON COLUMN ORGANIZE.CREATE_BY IS '创建人';
COMMENT ON COLUMN ORGANIZE.CREATE_DATE IS '创建时间';
COMMENT ON COLUMN ORGANIZE.UPDATE_BY IS '修改人';
COMMENT ON COLUMN ORGANIZE.UPDATE_DATE IS '修改时间';
COMMENT ON COLUMN ORGANIZE.DEL_FLAG IS '删除标识';
COMMENT ON TABLE ORGANIZE IS '组织机构信息';

declare
    num   number;
begin
    select count(1) into num from user_tables where table_name = upper('RESOURCES');
    if num > 0 then
        execute immediate 'drop table RESOURCES';
    end if;
end;
/
CREATE TABLE RESOURCES
(  ID           NUMBER(20)      NOT NULL,
   PARENT_ID    NUMBER(20),
   RES_CODE     VARCHAR2(64)    NOT NULL,
   RES_NAME     VARCHAR2(128)   NOT NULL,
   RES_DEST     VARCHAR2(256),
   RES_TYPE     NUMBER(1) DEFAULT 0,
   RES_ICON     VARCHAR2(64),
   RES_URL      VARCHAR2(128)   NOT NULL,
   SORT_NUM     NUMBER(8),
   CREATE_BY    NUMBER(20)      NOT NULL,
   CREATE_DATE  NUMBER(13)      NOT NULL,
   UPDATE_BY    NUMBER(20),
   UPDATE_DATE  NUMBER(13),
   DEL_FLAG     NUMBER(1) DEFAULT 0 NOT NULL,
   CONSTRAINT RESOURCES_PK PRIMARY KEY (ID)
 );
COMMENT ON COLUMN RESOURCES.ID IS '主键';
COMMENT ON COLUMN RESOURCES.PARENT_ID IS '上级编号';
COMMENT ON COLUMN RESOURCES.RES_CODE IS '资源编码';
COMMENT ON COLUMN RESOURCES.RES_NAME IS '资源名称';
COMMENT ON COLUMN RESOURCES.RES_DEST IS '资源描述';
COMMENT ON COLUMN RESOURCES.RES_TYPE IS '类型（菜单、权限）';
COMMENT ON COLUMN RESOURCES.RES_ICON IS '图标';
COMMENT ON COLUMN RESOURCES.RES_URL IS '资源地址';
COMMENT ON COLUMN RESOURCES.SORT_NUM IS '排序号';
COMMENT ON COLUMN RESOURCES.CREATE_BY IS '创建人';
COMMENT ON COLUMN RESOURCES.CREATE_DATE IS '创建时间';
COMMENT ON COLUMN RESOURCES.UPDATE_BY IS '修改人';
COMMENT ON COLUMN RESOURCES.UPDATE_DATE IS '修改时间';
COMMENT ON COLUMN RESOURCES.DEL_FLAG IS '删除状态';
COMMENT ON TABLE RESOURCES IS '资源菜单信息';

declare
    num   number;
begin
    select count(1) into num from user_tables where table_name = upper('ROLE_INFO');
    if num > 0 then
        execute immediate 'drop table ROLE_INFO';
    end if;
end;
/
CREATE TABLE ROLE_INFO
(  ID           NUMBER(20)      NOT NULL,
   ROLE_CODE    VARCHAR2(32)    NOT NULL,
   ROLE_NAME    VARCHAR2(64)    NOT NULL,
   ROLE_DEST    VARCHAR2(256),
   NEEDGA       NUMBER(1) DEFAULT 0,
   CREATE_BY    NUMBER(20)      NOT NULL,
   CREATE_DATE  NUMBER(13)      NOT NULL,
   UPDATE_BY    NUMBER(20),
   UPDATE_DATE  NUMBER(13),
   DEL_FLAG     NUMBER(1) DEFAULT 0,
   CONSTRAINT ROLE_INFO_PK PRIMARY KEY (ID)
);
COMMENT ON COLUMN ROLE_INFO.ID IS '主键';
COMMENT ON COLUMN ROLE_INFO.ROLE_CODE IS '角色编码';
COMMENT ON COLUMN ROLE_INFO.ROLE_NAME IS '角色名称';
COMMENT ON COLUMN ROLE_INFO.ROLE_DEST IS '角色描述';
COMMENT ON COLUMN ROLE_INFO.NEEDGA IS '需要GA验证 0不需要 1需要';
COMMENT ON COLUMN ROLE_INFO.CREATE_BY IS '创建人';
COMMENT ON COLUMN ROLE_INFO.CREATE_DATE IS '创建时间';
COMMENT ON COLUMN ROLE_INFO.UPDATE_BY IS '修改人';
COMMENT ON COLUMN ROLE_INFO.UPDATE_DATE IS '修改时间';
COMMENT ON COLUMN ROLE_INFO.DEL_FLAG IS '删除标识';
COMMENT ON TABLE ROLE_INFO IS '角色信息';

declare
    num   number;
begin
    select count(1) into num from user_tables where table_name = upper('USER_INFO');
    if num > 0 then
        execute immediate 'drop table USER_INFO';
    end if;
end;
/
CREATE TABLE USER_INFO
(  ID           NUMBER(20)      NOT NULL,
   USER_NAME    VARCHAR2(32)    NOT NULL,
   TRUE_NAME    VARCHAR2(64),
   PASSWORD     VARCHAR2(64)    NOT NULL,
   GENDER       NUMBER(1) DEFAULT 0,
   ACTIVE       NUMBER(1) DEFAULT 0,
   ID_CARD      VARCHAR2(18),
   LOGO         VARCHAR2(256),
   DEST         VARCHAR2(256),
   JOB_TITLE    VARCHAR2(32),
   ADDRESS      VARCHAR2(16),
   SIGN         VARCHAR2(50)    NOT NULL,
   RANDOM_KEY   VARCHAR2(8)     NOT NULL,
   AUTH_KEY     VARCHAR2(32),
   CREATE_DATE  NUMBER(13),
   UPDATE_DATE  NUMBER(13),
   DEL_FLAG     NUMBER(1) DEFAULT 0,
   CONSTRAINT USER_INFO_PK PRIMARY KEY (ID),
   CONSTRAINT USER_INFO_Unique_USER_NAME UNIQUE (USER_NAME)
);
COMMENT ON COLUMN USER_INFO.ID IS '主键';
COMMENT ON COLUMN USER_INFO.USER_NAME IS '用户名';
COMMENT ON COLUMN USER_INFO.TRUE_NAME IS '真实姓名';
COMMENT ON COLUMN USER_INFO.PASSWORD IS '密码';
COMMENT ON COLUMN USER_INFO.GENDER IS '性别';
COMMENT ON COLUMN USER_INFO.ACTIVE IS '激活状态';
COMMENT ON COLUMN USER_INFO.ID_CARD IS '身份证号';
COMMENT ON COLUMN USER_INFO.LOGO IS '头像';
COMMENT ON COLUMN USER_INFO.DEST IS '描述';
COMMENT ON COLUMN USER_INFO.JOB_TITLE IS '职称';
COMMENT ON COLUMN USER_INFO.ADDRESS IS '所在地址';
COMMENT ON COLUMN USER_INFO.SIGN IS '签名';
COMMENT ON COLUMN USER_INFO.RANDOM_KEY IS 'KEY';
COMMENT ON COLUMN USER_INFO.AUTH_KEY IS 'GOOGLE验证器私钥';
COMMENT ON COLUMN USER_INFO.CREATE_DATE IS '创建时间';
COMMENT ON COLUMN USER_INFO.UPDATE_DATE IS '修改时间';
COMMENT ON COLUMN USER_INFO.DEL_FLAG IS '删除标记';
COMMENT ON TABLE USER_INFO IS '用户基础信息';

declare
    num   number;
begin
    select count(1) into num from user_tables where table_name = upper('ROLE_RES');
    if num > 0 then
        execute immediate 'drop table ROLE_RES';
    end if;
end;
/
CREATE TABLE ROLE_RES
(  ID       NUMBER(20)  NOT NULL,
   ROLE_ID  NUMBER(20)  NOT NULL,
   RES_ID   NUMBER(20)  NOT NULL,
   CONSTRAINT ROLE_RES_PK PRIMARY KEY (ID)
);
COMMENT ON COLUMN ROLE_RES.ID IS '主键';
COMMENT ON COLUMN ROLE_RES.ROLE_ID IS '角色ID';
COMMENT ON COLUMN ROLE_RES.RES_ID IS '资源ID';
COMMENT ON TABLE ROLE_RES IS '角色权限信息';

declare
    num   number;
begin
    select count(1) into num from user_tables where table_name = upper('USER_ROLE');
    if num > 0 then
        execute immediate 'drop table USER_ROLE';
    end if;
end;
/
CREATE TABLE USER_ROLE
(  ID       NUMBER(20)  NOT NULL,
   USER_ID  NUMBER(20)  NOT NULL,
   ROLE_ID  NUMBER(20)  NOT NULL,
   CONSTRAINT USER_ROLE_PK PRIMARY KEY (ID)
);
COMMENT ON COLUMN USER_ROLE.ID IS '主键';
COMMENT ON COLUMN USER_ROLE.USER_ID IS '用户ID';
COMMENT ON COLUMN USER_ROLE.ROLE_ID IS '角色ID';
COMMENT ON TABLE USER_ROLE IS '用户角色权限';

declare
    num   number;
begin
    select count(1) into num from user_tables where table_name = upper('USER_DATA');
    if num > 0 then
        execute immediate 'drop table USER_DATA';
    end if;
end;
/
CREATE TABLE USER_DATA
(  ID       NUMBER(20)  NOT NULL,
   USER_ID  NUMBER(20)  NOT NULL,
   ORG_ID   NUMBER(20)  NOT NULL,
   CONSTRAINT USER_DATA_PK PRIMARY KEY (ID)
);
COMMENT ON COLUMN USER_DATA.ID IS '主键';
COMMENT ON COLUMN USER_DATA.USER_ID IS '用户ID';
COMMENT ON COLUMN USER_DATA.ORG_ID IS '机构ID';
COMMENT ON TABLE USER_DATA IS '数据权限信息';
