server:
  port: 8080
  http2:
    enabled: true
  servlet:
    context-path: /api
spring:
  application:
    name: GamsBossServer
  redis:
    cluster:
      nodes: @cluster.nodes@
      max-redirects: 3
    host: @redis.host@
    port: @redis.port@
    password: @redis.password@
    timeout: @redis.timeout@
    conn-type: @redis.conntype@ # cluster/single
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 2
        # 连接池中的最大空闲连接
        max-idle: 500
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 2000
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 10000
com:
  gams:
    open-log: true
    project-name: boss
    aliyun:
      app-key: @aliyun.afs.appkey@
      access-key: @aliyun.access.key@
      secret-key: @aliyun.access.secret@
      end-point: @aliyun.oss.endpoint@
#      bucket:
#        release-name:
#        release-url:
#        temp-name:
#        temp-url:
    amazon:
      access-key: @amazon.access.key@
      secret-key: @amazon.access.secret@
      bucket:
        release-name: @amazon.bucket.release-name@
        release-url: @amazon.bucket.release-url@
        temp-name: @amazon.bucket.temp-name@
        temp-url: @amazon.bucket.temp-url@
  alipay:
    sofa:
      rpc:
        registry-address: @zookeeper.address@
logging:
  path: logs/boss
  level:
    com.fintech: @gams.logger.level@
    com.alipay: info
    org.apache: info
    springfox: error
  pattern:
    console: "[%d{yyyy-MM-dd HH:mm:ss:SSS}] [%p] - %pid - %l - %m%n"